version: '3.9'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'db'
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '04012002'
      POSTGRES_DB: 'NewtechShop'
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80

    ports:
      - '5050:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

# a location in local filesystem that is managed by docker. Volume is used persist daa of postgres container even
# if user delete and recreate it
volumes:
  # refer volume in docker
  postgres:
  pgadmin:
